{
  "source_dir": "programs",
  "files": {
    "programs/input.txt": "41\n"
  },
  "expected_files": {
    "programs/nested/output.txt": "42\n"
  },
  "memory": {
    "INPUT_FILE": {
      "path": "input.txt",
      "mode": null,
      "open": false
    },
    "OUTPUT_FILE": {
      "path": "nested/output.txt",
      "mode": null,
      "open": false
    },
    "VALUE": 41
  },
  "output": "41\n",
  "exitcode": 0
}
